java_package: "openjdk-17-jdk"
gradle_version: " 8.14.3"
repo_url: "https://github.com/jpedroal11/cogsi2425-1211066-1250515-1181754-1220638.git"
app_dir: "/home/vagrant/app"
project_dir: "{{ app_dir }}/CA4/ca2-part2/"
